### ISSUE TITLE
Missing architectures

### ISSUE THREAD

**Issue by victorjussiani** [kontaktio/SDK-iOS#1]
When i try to run the example project on my Xcode Version 6.1.1, i got the following error:

```
libkontakt-ios-sdk.a, missing required architecture x86_64
```

Then i run command ```lipo -info libkontakt-ios-sdk.a``` and see that are just two architectures available: armv7 arm64.

Could you build to armv7s i386 x86_64 arm64 ?

Thanks

**Comment by jeffreyjackson** [comment]
Just fix your ld flags and you should be fine

**Comment by victorjussiani** [comment]
My architectures flags seems like this and the error persist, what am i doing wrong?

![architecture](https://cloud.githubusercontent.com/assets/2778356/6584138/935a7dac-c73f-11e4-8dd9-f0bd08ab98cb.png)

**Comment by hlebowicz-kontakt** [comment]
Hi guys,

We did it with a purpose that lib is NOT build against x86 architecture.
It's due to the fact that BL is not working in iOS Simulator.

Easiest solution is to plug in your device and build your project for it.

That said, today we will release lib with x86 architecture but keep in mind that all BL stuff won't be working in simulator.

**Comment by victorjussiani** [comment]
Thank you, I understand that will not work in the simulator.

I'm waiting for the new release.

**Comment by hlebowicz-kontakt** [comment]
It's already updated and waiting for you.
Still keep in mind that BL stuff is not working in simulator.

**Comment by victorjussiani** [comment]
Perfect, is now operating normally.

And it was much better with the CocoaPods now , thank you.
