### ISSUE TITLE
App doesn't receive background updates

### ISSUE THREAD

**Issue by Meltor22** [kontaktio/SDK-iOS#8]
I'm using Kontakt iBeackons and try go fetch background updates from the beacons.

- I used NSLocationAlwaysUsageDescription in plist.info
- [[UIApplication sharedApplication] backgroundRefreshStatus]; returns UIBackgroundRefreshStatusAvailable

Which function should be called?
Could you send a working example?

**Comment by hlebowicz-kontakt** [comment]
I believe you should just dig deeper in our quickstart http://docs.kontakt.io/ios-sdk/quickstart/

**Comment by Meltor22** [comment]
A more detailed answer would be appreciated a lot.
I read the whole quickstart document. Updates are working if the app is in foreground, but i don't receive updates if the app is in background. And i haven't found a specific topic in the quickstart how to receive the background updates. (only how to enable them)

**Comment by hlebowicz-kontakt** [comment]
You don't have to do any additional actions to get updates from beacons in the background.
In BG mode you should receive events like enter/exit region which means the methods that will be called are:
    - (void)locationManager:(KTKLocationManager *)locationManager didEnterRegion:(KTKRegion *)region;
    - (void)locationManager:(KTKLocationManager *)locationManager didExitRegion:(KTKRegion *)region;
from KTKLocationManager.
If you will receive enter event additionally will be called(for few times):
    - (void)locationManager:(KTKLocationManager *)locationManager didRangeBeacons:(NSArray *)beacons;
I hope now it's more clear.

**Comment by Meltor22** [comment]
Hi,
tracked down the bug a litte more in detail now. You’r right i receive updates from beacons in background.

But only on the first app start (when the user get’s asked to permit access to location services)
If the get’s stopped/killed/crashed and gets restarted afterwards no background events are received anymore.

In didChangeState the state KTKLocationManagerStateMonitoring get’s received at relaunch of the app. Then only foreground updates are received, if the app get’s into background no updates are received anymore.

Any hints?

**Comment by hlebowicz-kontakt** [comment]
Hi @Meltor22,

It's strange behavior because there is no dependency between first run with Location Updates dialog and monitoring in the background.

Maybe you have something wrong with setting regions after app's restart?

Try to have at least 2 different proximities set on your beacons. Then after app restart turn off(take battery off) the beacon with this 2nd unique proximity UUID - after you'll receive **didExitRegion** go to background and turn on the beacon(put battery back) - you should receive **didEnterRegion**.

Let me know if you succeeded with it.
